server:
  port: 5161
spring:
  datasource:
    url: jdbc:mariadb://3.34.162.209:3306/todo
    driver-class-name: org.mariadb.jdbc.Driver
    username: jang
    password: wkdguswns
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
#    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update