server:
  port: 5161
spring:
  datasource:
    url: jdbc:mariadb://13.125.176.63/todo
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: wkdguswns
  jpa:
    database-platform: org.hibernate.dialect.MariaDB53Dialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update